- generative/random.hlsl
- math/grad4.hlsl
`grad4.glsl` didn't have a parallel HLSL version, adding that.
Note: 
I had to make the following change, because HLSL doesn't have a `lessThan` function:
```
// 1 - step(y, x) is the same as (x < y)
// GLSL: s = float4(lessThan(p, float4(0.0)));
s = float4(1 - step(float4(0, 0, 0, 0), p));
```
Also making some changes to `random.hlsl`, which had some `float{n}` constructors with a single argument.
> Add HLSL version of grad4, initializer fix in random.hlsl

- color/space/YPbPr2rgb.hlsl
- color/space/cmyk2rgb.hlsl
- color/space/rgb2cmyk.hlsl
- generative/noised.hlsl
- generative/snoise.hlsl
- math/mod.hlsl
- math/permute.hlsl
- sdf/rhombSDF.hlsl
There were some `vec{n}` references in HLSL files, correcting them.
> Some HLSL type fixes in code + comments

- color/hueShift.glsl
- color/hueShift.hlsl
Small typo in `hueShift.glsl` and `hueShift.hlsl`
There's an extra``` at the end :)
> Fix typo in hueShift.glsl/hlsl

- lighting/light/point.glsl
Same as before: if the PBR shader is included outside Viewer, this variable will be undefined. My understanding is that this mechanism allows to include in 'stock' configuration and override for custom use
> Default SURFACE_POSITION to vec3(0.0)

- sample/viewPosition.glsl
- sample/viewPosition.hlsl
In this PR, I support pass `depth` into `sampleViewPosition`.
On iOS 14-, the `WEBGL_depth_texture` extension has poor extension and we need to pack float to rgba8, and unpack it when we want to use it.
So it will be useful if we support passing `depth` directly.
One more thing, the old `sampleViewPosition` return type is wrong, and it has been fixed in this PR.
> feat: enhance sampleViewPosition

- space/linearizeDepth.glsl
- space/linearizeDepth.hlsl
From https://learnopengl.com/Advanced-OpenGL/Depth-testing, the linearize depth formula is
```glsl
float ndc = depth * 2.0 - 1.0; 
float linearDepth = (2.0 * near * far) / (far + near - ndc * (far - near));
```
The code is missing `* far` part.
> fix: linearizeDepth wrong

- space/triTile.glsl
Adding a triTile function for creating triangle shaped tiles as suggested in #45 
- Loosely inspired by FabriceNeyret2 hexagonal tiling tuto https://www.shadertoy.com/view/4dKXR3
- The coords are skewed by the rotation matrix used to create the triangles. If might be nice if the output coords weren't skewed so the user can make non-skewed shapes inside the triangles. If anyone has a suggestion how to do that it would be most welcome! 
- I'm not familiar with the hlsl language and haven't got a setup to test it, can you make the translation @patriciogonzalezvivo?
> feat: adding triTile

- draw/aastep.glsl
Hello,
Since `OES_standard_derivatives` extension is not present in OpenGL ES 3 (WebGL 2) and regular OpenGL it will wrongfully fallback to `step()`, so I tweaked the preprocessing checks to properly target the environment.
Sources:
https://registry.khronos.org/OpenGL-Refpages/gl4/html/fwidth.xhtml
https://registry.khronos.org/OpenGL-Refpages/es3.0/html/fwidth.xhtml
https://registry.khronos.org/OpenGL/extensions/OES/OES_standard_derivatives.txt
https://www.khronos.org/files/opengles_shading_language.pdf (page 12)
> Fix aastep for WebGL2 and non-es OpenGL

- sample.glsl
- sample.hlsl
Fix #58 
This PR removes `sample()` definition (as I didn't find any usage reference of `FNC_SAMPLE` in the source code), but IDK what's the best choice for Lygia, I only wanted to highlight the issue.
> fix: "sample: Illegal use of reserved word" on WebGL shaders

- lighting/raymarch/cast.glsl
Hello,
I've added new macros to configure raymarching distance parameters, because the provided fixed values are unsuitable for each case.
> feat(raymarchCast): template distance parameters and better default values

- lighting/fakeCube.glsl
- lighting/raymarch.glsl
Resolve custom fakecube uv undeclared error that previously use 'd' variable instead of '_normal'. Also fix the typo issue raised by `Lutymane:patch-1` https://github.com/patriciogonzalezvivo/lygia/pull/61 .
I tried your custom fake cube! LOVE IT!! 🚀🥳 I've been searching for this method for me to do custom fakeCube without using samplerCube/cubemap texture by using `envMap` function!
> Fakecube fix & typos

- README.md
Per your suggestion in the issue #44,
added another way of cloning LYGIA to README. The degit command will exclude git history to save project size (about 9MB) and download faster.
> Update README.md to add degit instruction

- geometry/aabb.glsl
- geometry/aabb.hlsl
- geometry/aabb/centroid.hlsl
Hi,
This small PR fixes broken includes in aabb.glsl and aabb.hlsl (`aabb/center.*` instead of `aabb/centroid.*`), as well as a typo in the `use` field of the documentation of `centroid.hlsl` (`centrood` instead of `centroid`).
Regards, TJ
> Fix broken include paths

- lighting/raymarch/glass.glsl
- lighting/raymarch/glass.hlsl
I'm so sorry that I am bothering your day. It seems that my example shader is not loaded properly here: https://lygia.xyz/lighting/raymarch/glass .
So I thought, the format of my example link is not loaded correctly due to the extra character `|` before the file relative link. I also remove some useless code & did refactoring for flexibility. I hope you can merge this with ease! 🥳
> Hotfix Raymarch Glass

- sdf/kochSDF.glsl
- sdf/kochSDF.hlsl
While this  is not an exact copy of The Art of Code's version of the Koch curve,  it is essentially his code.  I have added if statements to choose different iterations.  I couldn't find a function that returned vec2(sin(angle), cos(angle)).  Please let me know if there is one that can be utilized.
> Add koch sdf

- color/dither/blueNoise.glsl
- color/dither/blueNoise.hlsl
removed an unnecessary underscore character in the SAMPLER_FNC call on ln 67 in color/dither/blueNoise.glsl
> fix typo on SAMPLER_FNC function call

- sample/marchingSquares.glsl
Hey @patriciogonzalezvivo I've added a first version of a marching squares algorithm. Would love to get some feedback on naming, code improvements, potential performance improvements and everything else that comes to your mind ✌🏽 
I've also put up an example on how to use it over at my [examples.lygia-threejs](https://github.com/guidoschmidt/examples.lygia-threejs) repo.
> ADD/sample/marchingSquares.glsl: first draft of marching squares algorithm

- math/scale3d.glsl
Its possible this issue exists in various other files if it exists in this one.
> fix: remove trailing commas in scale3d.glsl

- color/space/rgb2yiq.hlsl
I'm starting to go through the old unity samples and update them to the latest lygia. There are a few hlsl errors that are failing to compile. Some have me stumped, but I'll try to push up the simple ones like this as I get through them.
> removed unterminated define in rgb2yiq.hlsl

- math/mix.hlsl
-renamed lerp to mix to not collide with hlsl lerp.
-replaced unsupported recursive functions
> fix for math/mix.hlsl not compiling in unity

- color/space/rgb2srgb.hlsl
- color/space/srgb2rgb.hlsl
closes #103 
I'm not sure why this is an issue to begin with. These are getting imported into the same compilation unit when they collide. For some reason #ifndef isn't working properly across them.
> redefined epsilon in colliding files

- color/vibrance.glsl
Fixes what appears to be a refactor oversight at https://github.com/patriciogonzalezvivo/lygia/commit/1bed3df3091647377bfa5e9fe55bfb4e93381483.
> Fix: undeclared 'color' identifier in vibrance.glsl

- filter/sharpen/fast.glsl
- filter/sharpen/fast.hlsl
Small typo regarding sharpening "strength"
> fix typo in sharpen/fast.glsl

- color/space/rgb2oklab.glsl
- color/space/rgb2oklab.hlsl
- color/space/rgb2oklab.wgsl
I was attempting to `#include "lygia/color/space.glsl"` in the editor on lygia.xyz and got the error: 'rgb2oklab' : function does not return a value.
I noticed these functions were missing 'return' statements.
> Fix missing return statemtent for rgb2oklab.

- color/space/srgb2lch.glsl
- color/space/srgb2lch.hlsl
> Fix undeclared identifier in srgb2lch funcs.

- color/space/hsv2rgb.hlsl
- color/space/yiq2rgb.hlsl
Both functions were broken because of typos in variable names.
> Fixed typo bugs in hlsl versions of yiq2rgb and hsv2rgb

- filter/bilateral.hlsl
Parameter order was inverted when calling `float gaussian(float3 d, float sigma)`
> Fixed hlsl implementation of filter/bilateral.

- lighting/pbrLittle.glsl
- lighting/pbrLittle.hlsl
Fixed lighting/pbrLittle. The indirect diffuse component (spherical harmonics) should be added to direct diffuse, not multiplied by it.
> Fixed pbrLittle indirect diffuse.

- lighting/fresnel.glsl
- lighting/fresnel.hlsl
Added a roughness-adjusted fresnel function. This function has been described by Sébastien Lagarde and others.
The rationale is as follows: "Applying Fresnel term to prefiltered cubemap has a bad effect of always showing high specular color at edge, even for rough surface.... We approximate this “fresnel attenuation” empirically by introducing a fudge factor (taking count of gloss) in fresnel equation to get pleasant visual result"
This produces significant improvements when applied to the indirect components of a PBR shader.
For more details, see Lagarde's blog post.
https://seblagarde.wordpress.com/2011/08/17/hello-world/
> Roughness-adjusted fresnel.

- lighting/camera.glsl
- lighting/camera.hlsl
- lighting/common/envBRDFApprox.hlsl
- lighting/common/specularAO.hlsl
- lighting/envMap.hlsl
- lighting/fresnelReflection.hlsl
- lighting/light/directional.hlsl
- lighting/light/new.hlsl
- lighting/light/point.hlsl
- lighting/light/resolve.hlsl
- lighting/material.hlsl
- lighting/material/new.hlsl
- lighting/pbr.hlsl
- lighting/pbrClearCoat.hlsl
Complete overhaul of the HLSL PBR shader to align with the GLSL Version. This includes the following dependencies:
* Ported LightPoint struct to point.hlsl
* Ported LightDIrection struct to directional.hlsl
* Ported cache fields to material.hlsl
* Ported support for Material struct in point.hlsl, directional.hlsl, fresnelReflection.hlsl and envMap.hlsl
* Ported support for Material struct in specularAO and updated signature to match glsl
* Ported new.hlsl
* Ported resolve.hlsl
* Ported and updated envBRDFApprox.hlsl
* Finally ported pbr.hlsl from glsl
> Complete overhaul of the HLSL PBR shader to align with the GLSL Version.

- lighting/light/directional.glsl
- lighting/light/directional.hlsl
- lighting/light/point.glsl
- lighting/light/point.hlsl
- lighting/pbr.glsl
- lighting/pbr.hlsl
Some fixes and visual tweaks to the PBR shader.
I back-to-backed the HLSL version against the Unity Standard Shader and my own PBR implementation (based on the Karis UE4 variant).
1. Fixed the Unity light direction in the HLSL version. It was flipped in PR #151 (my bad!)
2. Tweaked the indirect specular component (glsl and hlsl). I'm not sure what was the rationale for the previous implementation. The new one conforms to the Brian Karis article (https://www.unrealengine.com/en-US/blog/physically-based-shading-on-mobile) and in any case looks much better.
3. As it's currently implemented, the contribution of point and directional light (direct specular and direct diffuse) doesn't look correct to me. It is missing a multiplication by `dot(N, L)`. I added that to point and directional …
> PBR fixes and visual tweaks.

- lighting/gooch.glsl
- lighting/light/directional.hlsl
- lighting/light/point.hlsl
- lighting/pbrClearCoat.glsl
- lighting/pbrClearCoat.hlsl
* Straightforward port of pbrClearCoat.hlsl from glsl version
* Applied fix to specular indirect from #152  to pbrClearCoat (GLSL and HLSL versions)
* Cleaned-up obsolete functions in point.hlsl and directional.hlsl.
> Updated pbrClearCoat to bring it in line with the latest glsl version.

- lighting/envMap.hlsl
- lighting/fresnelReflection.hlsl
Changed the envMap cubmap texture type declaration from the obsolete DirectX 9 (2002) syntax to the newer DirectX 11 (2009) syntax.
This requires clients to update the cubemap declaration on their end from
`samplerCUBE _Cube;`
to
`TextureCube _Cube;`
`SamplerState sampler_Cube;`
This allows us to query the TextureCube object for the max Mip Level.
Currently Lygia assumes a default ENVMAP_MAX_MIP_LEVEL of 3, which is:
1. Dependent on the resolution of the texture
2. Very low for typical 2k cubemap textures.
This results in cubemaps not being sufficiently blurred when using rough materials.
The new system is resolution independent and guarantees correct blurring levels.
ENVMAP_MAX_MIP_LEVEL can still be used to override the automatic setting if desired.
> envMap automatic MIP level (HLSL Only)

- math/fcos.glsl
- math/fcos.hlsl
Added IQ's band-limited variant of `cos(x)` which dramatically reduces aliasing at high frequencies.
Copied as is from Inigo's 2020 article https://iquilezles.org/articles/bandlimiting/
`cos(x)` wave aliasing at high frequencies
`fcos(x)` replacement
> fcos(x): band-limited cos(x), GLSL and HLSL

- color/dither/blueNoise.hlsl
- color/lut.hlsl
- color/space/rgb2xyz.hlsl
- math/pack.hlsl
- math/unpack.hlsl
The sequel to #157 All `const` variables are now `static const`, preventing them from being discarded by the HLSL compiler.
> Added more missing static keywords (HLSL only).

- math/aafract.glsl
- math/aafract.hlsl
- math/nyquist.glsl
- math/nyquist.hlsl
Another take at band-limiting aafract with a slightly different approach. This time I kept the existing algorithm but tacked a low-pass filter to it, centered on the Nyquist frequency (half a pixel).
Summary of changes:
* Added nyquist.glsl and nyquist.hlsl (low-pass filters)
* Calling nyquist() in aafract (+some refactoring of the unnecessary map() call)
* Using the L2 norm instead of L1 (width) in aafract.hlsl, in line with aafract.glsl
Without band-limiting:
With bandlimiting:
> Band-limited aafract (2nd approach)

- math/aamirror.glsl
- math/aamirror.hlsl
In the spirit of previous improvements to aafract, I added an anti-aliased and band-limited variant of math/mirror. Since this is a full rethink and rewrite of the function, and to emphasize the antialiased nature of the function and similarity to aafract and co., I named it aamirror.
math/mirror
math/aamirror
> Anti-aliased triangle wave (GLSL and HLSL)

- generative/worley.glsl
- generative/worley.hlsl
Currently, the `worley` function returns `1.0-F1` where F1 is the distance of a given point (which coordinates are passed as input param) to the closest seed point).
I modified it slightly to return `vec2(F1, F2)`, that is, the distances to the closest and second closest seed point, respectively.
This hands us a variety of noise patterns in a single function call (and very little overhead). F1 and F2 can be combined in many fun ways, including `F2-F1` which produces a lovely terrazzo-like pattern and can be thresholded to mimic scratches and wear.
I also added a WORLEY_JITTER option to modify the randomness of the Voronoi diagram, all the way down to 0, which results in a perfectly symmetrical pattern. The default is 1.0 (which is equivalent to the current behaviour).
These examples below …
> Moar Noise, plz!

- lighting/diffuse/lambert.hlsl
- lighting/fresnelReflection.glsl
- lighting/fresnelReflection.hlsl
- lighting/light/point.glsl
- lighting/light/point.hlsl
- lighting/material.glsl
- lighting/material.hlsl
- lighting/material/new.glsl
- lighting/material/new.hlsl
- lighting/pbrGlass.glsl
- lighting/pbrGlass.hlsl
* Bringing pbrGlass.hlsl and dependencies up-to-date with the glsl version, particularly support for SHADING_MODEL_IRIDESCENCE
* Support for SHADING_MODEL_SUBSURFACE in pbr.hlsl (ported from glsl)
* Bugfix to SHADING_MODEL_SUBSURFACE in glsl when used with point lights.
> Updates to pbrGlass and pbr (HLSL)

- lighting/envMap.hlsl
- sampler.hlsl
Currently `SAMPLER_TYPE` is defined in HLSL as sampler2D, which is the obsolete DirectX 9 syntax from 2002.
This works fine with the old Unity Built-In render pipeline (BRP), which is itself deprecated.
However, it is not compatible with the newer URP and HDRP pipelines which are meant to supersede BRP. URP and HDRP use the Direct X 10 syntax (released in 2006).
Direct X 10 replaces the old `sampler2D` with Texture objects (eg. `Texture2D`) which also provide added benefits, like decoupling the texture object from the sampler state, querying size and max lod, etc...
Unreal also uses the DirectX 10 syntax exclusively.
This means texture-related functions in Lygia are currently unusable with Unity URP, Unity HDRP and Unreal.
I have updated the samplers to the DirectX 10 syntax in order to …
> Updated HLSL samplers to DirectX 10 syntax

- sample.glsl
- sample.hlsl
- sample/normalFromTexture.glsl
- sample/normalFromTexture.hlsl
When displacing a grid based on a height map texture, we need to calculate the normals. This function does it for us.
Here's an example of 2048x2048 grid being displaced by a simple noise texture. Normals are calculated directly from the height maps using sample/normalFromTexture.
> New feature: calculate normal from height map (GLSL and HLSL)

- lighting/raymarch.hlsl
- lighting/raymarch/camera.hlsl
Ok, this one gave me a hard time 😅
Raymarching camera was broken in hlsl and rotating in erratic ways when moved.
Turns out the culprit was matrix layout in `raymarch/camera.hlsl`:
glsl is row-major anh hlsl column major. The returned `float3x3` is initialised with row vectors, but `cu`, `cv` and `cw` are column vectors. Thus, we need to transpose the matrix before returning it (HLSL only).
There might def be similar errors elsewhere in the HLSL, I'll try to find a moment to track them down.
> Fixed raymarching camera (HLSL)

- generative/cnoise.wgsl
I originally ported it in my WebGPU engine a few years back:
https://github.com/dmnsgn/dgel/blob/main/src/shaders/noise/classic.wgsl.ts
And tested it with the following example: https://dmnsgn.github.io/dgel/?id=instancing
Let me know if I need to update the contributors list or any other form of docs.
> feat: add cnoise wgsl

- lighting/raymarch/softShadow.glsl
- lighting/raymarch/softShadow.hlsl
* Improved raymarching soft shadow quality
* Exposed more more shadow params:
- RAYMARCH_SHADOW_MIN_DIST: minimum shadow distance
- RAYMARCH_SHADOW_MAX_DIST: maximum shadow distance
- RAYMARCH_SHADOW_SOLID_ANGLE: light size
This is ported from Inigo's article  [soft shadows in raymarched SDFs](https://iquilezles.org/articles/rmshadows/)
Before (notice the unrealistic shadow of the prism)
After
> Improved raymarching shadow quality (HLSL and GLSL)

- lighting/light/directional.glsl
- lighting/light/directional.hlsl
- lighting/light/point.glsl
- lighting/light/point.hlsl
- lighting/pbr.glsl
- lighting/pbr.hlsl
- lighting/raymarch/material.glsl
- lighting/raymarch/material.hlsl
When using PBR with raymarching, soft shadows and ambient occlusion can be turned on with
- `#define RAYMARCH_SHADOWS`
- `#define RAYMARCH_AO`
Default raymarching material
Raymarched PBR
Raymarched PBR with soft shadows
Raymarched PBR with soft shadows and AO
> Added shadow and support to Raymarched PBR

- lighting/diffuse/lambert.hlsl
- lighting/raymarch/volume.glsl
- lighting/raymarch/volume.hlsl
- sdf.hlsl
- sdf/flowerSDF.hlsl
* Fixed `flowerSDF.hlsl` (`float2` instead of `vec2`)
* Fixed include in `lambert.hlsl`
* Added missing includes to `sdf.hlsl`
* Fixed include in `volume.sdf` (`saturate` is a built-in in HLSL)
* Parametrised `raymarchMap` in `volume.hlsl` `volume.glsl`
> Various HLSL SDF Fixes

- lighting/envMap.glsl
- lighting/envMap.hlsl
This is a follow-up to #154 and implements similar functionality in GLSL. Unlike the HLSL version, no changes are required on the user's end. For incompatible systems (OpenGL < 4.3) we automatically revert to the old behaviour.
As a reminder:
Currently Lygia assumes a default ENVMAP_MAX_MIP_LEVEL of 3, which is:
Dependent on the resolution of the texture
Very low for typical 2k cubemap textures.
This results in cubemaps not being sufficiently blurred when using rough materials.
The new system is resolution independent and guarantees correct blurring levels.
ENVMAP_MAX_MIP_LEVEL can still be used to override the automatic setting if desired.
> envMap automatic MIP level (GLSL)

- lighting/pbr.glsl
- lighting/pbr.hlsl
Currently, the PBR shader expects SCENE_SH_ARRAY (the spherical harmonics array) to be defined and will fail if not (the indirect diffuse component is broken).
An elegant fallback is to sample the environment at a high LOD level.
> PBR: fallback to environment sampling if Spherical Harmonics are not present.

- lighting/raymarch.glsl
- lighting/raymarch.hlsl
- lighting/raymarch/cast.glsl
- lighting/raymarch/cast.hlsl
This one is a bit tricky as it will affect existing scenes, but I think it’s something we’ll have to grapple with sooner or later.
There are 3 issues:
1. In `lighting/raymarch`, the camera position is being multiplied by a factor named `RAYMARCH_CAMERA_SCALE` which defaults to an apparently arbitrary `0.11`. Unless I’m missing something, I can’t see the rationale or the usefulness of this. But more importantly, it leads to the scene and the camera having different coordinate systems. It’s as if the scene is specified in meters and the camera in cms (except the factor is 0.11, not 0.1).
For a 1m quad to cover a 60 degrees camera viewport, the camera currently needs to be positioned 7.89m away which is absurd and counter-intuitive (some basic trigonometry shows it should be just 0.86m)
2. …
> Changes to raymarching camera FOV

- lighting/common/specularAO.glsl
- lighting/common/specularAO.hlsl
- lighting/fresnelReflection.glsl
- lighting/fresnelReflection.hlsl
- lighting/raymarch/ao.glsl
- lighting/raymarch/ao.hlsl
Replaced broken Raymarching AO implementation (HLSL and GLSL)
The new implementation is from IQ's Shadertoy [Soft Shadow Variation ](https://www.shadertoy.com/view/lsKcDD).
Bonus tracks:
* Fixed fresnelReflection with custom FRESNEL_REFLECTION_FNC
* Added link to specularAO
Before (notice the weird and unrealistic shadow at the bottom),
After
> Fixed Raymarching AO

- lighting/raymarch.glsl
- lighting/raymarch.hlsl
- lighting/raymarch/material.glsl
- lighting/raymarch/material.hlsl
- lighting/raymarch/render.glsl
- lighting/raymarch/render.hlsl
Added AOV (Arbitrary Output Variables) output support to the Raymarching engine.
These additional buffers are very useful for post-processing passes. And the good news: they come almost for free, as raymarching already provides us with this data!
We now have:
Color
Alpha
Eye Depth
World Position
World Normals
And finally, to illustrate, some DOF fun using the Eye Depth AOV and Lygia's sample/dof
> Added AOV output support to the Raymarching engine

- math/rotate2d.glsl
- math/rotate2d.hlsl
- math/rotate3d.glsl
- math/rotate3dX.glsl
- math/rotate3dX.hlsl
- math/rotate3dY.glsl
- math/rotate3dY.hlsl
- math/rotate3dZ.glsl
- math/rotate3dZ.hlsl
- math/rotate4d.glsl
- math/rotate4dX.glsl
- math/rotate4dX.hlsl
- math/rotate4dY.glsl
- math/rotate4dY.hlsl
- math/rotate4dZ.glsl
- math/rotate4dZ.hlsl
GLSL rotate functions were incorrectly transposed.
I took the opportunity to optimise both the GLSL and HLSL versions.
For reference the rotation matrices are (Source: [Wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix)):
I think I got it all right, but @patriciogonzalezvivo please feel free to double-check.
$$R(\theta) = \begin{bmatrix}
\cos\theta & -\sin\theta \\
\sin\theta & \cos\theta
\end{bmatrix}$$
$$\begin{bmatrix}
1 & 0 & 0 \\
0 & \cos\theta & -\sin\theta \\
0 & \sin\theta & \cos\theta
\end{bmatrix}_x$$
$$\begin{bmatrix} \cos\theta & 0 & \sin\theta \\
0 & 1 & 0 \\
-\sin\theta & 0 & \cos\theta
\end{bmatrix}_y$$
$$\begin{bmatrix}
\cos\theta & -\sin\theta & 0 \\
\sin\theta & \cos\theta & 0 \\
0 & 0 & 1
\end{bmatrix}_z$$
(sorry, too lazy to type this in Latex)
GLSL matrices …
> Fixed and optimised rotate functions.

- generative/wavelet.wgsl
Tested, properly, issue was `let` vs `var` bindings for mutable variables.
> fix bug in wavelet impl

- generative/worley.wgsl
- math/dist.wgsl
Tested, properly, issues were:
- `let` vs `var` bindings for mutable variables
- `dist` function calls non-existent overloaded function from glsl impl
- `worley2`, `worley3` call wrong function
> fix bug in worley impl

- filter/boxBlur.msl
- filter/boxBlur/1D.msl
- filter/boxBlur/2D.msl
- filter/boxBlur/2D_fast9.msl
- filter/gaussianBlur.msl
- filter/gaussianBlur/1D.msl
- filter/gaussianBlur/1D_fast13.msl
- filter/gaussianBlur/1D_fast5.msl
- filter/gaussianBlur/1D_fast9.msl
- filter/gaussianBlur/2D.msl
- math/gaussian.msl
- sample/clamp2edge.msl
- sampler.msl
Finally had a moment to work on this.
* had to add a `SAMPLER` which metal uses, which defaults to `sampler( min_filter::linear, mag_filter::linear )`
* set the default texture2d precision to float to keep things in parity with the rest of Lygia. This means that metal shaders need to define their texture as float, not half which is maybe more standard. You can override this by redefining `SAMPLER_TYPE`
Implemented box blur and gaussian blur just to test the waters.
> Feature/metal - some sampler + filter additions 

- lighting/raymarch.glsl
- lighting/raymarch.hlsl
- lighting/raymarch/render.hlsl
- space/translate.glsl
* Fixed viewMatrix column order issue in GLSL. This was causing the cameraForward to be incorrectly calculated and breaking eyeDepth.
* Fixed HLSL bug caused by https://github.com/patriciogonzalezvivo/lygia/commit/43fc57f9b645182dcd155052e90fb345ec76f94e. Gentle reminder to always make global `const` variables `static const` in HLSL. Otherwise they will be optimised away by the compiler and cause the shader to silently fail.
> Fixed viewMatrix issue (GLSL) and Raymarching bug (HLSL)

- lighting/pbr.glsl
- lighting/pbr.hlsl
- lighting/pbrClearCoat.hlsl
* AO was being applied twice. It should only be applied to the indirect component.
* raymarchAO was being called twice in the HLSL version.
> Fixed Ambient Occlusion in PBR

- lighting/raymarch/ao.glsl
- lighting/raymarch/ao.hlsl
- lighting/raymarch/normal.glsl
- lighting/raymarch/normal.hlsl
- lighting/raymarch/softShadow.glsl
- lighting/raymarch/softShadow.hlsl
On a quest to remove all magic numbers from the raymarching code and expose them as meaningful parameters whenever possible:
* Exposed offset param in `normal`
* Exposed all magic number in `ao` as params
* Refactored `softShadow`params.
> Minor param refactoring in Raymarch

- color/luminance.glsl
- color/tonemap/debug.glsl
- color/tonemap/filmic.glsl
- color/tonemap/reinhard.glsl
- color/tonemap/reinhardJodie.glsl
- lighting/envMap.glsl
- lighting/light/iblEvaluate.glsl
- lighting/pbrLittle.glsl
- lighting/specular/importanceSampling.glsl
- math/hammersley.glsl
- space/lookAt.glsl
- space/lookAt.hlsl
- space/lookAt.msl
Took some minor work to make this work correctly on ThreeJS. Mayor changes are:
* ThreeJS inject a `float luminance(vec3)` function. Unfortunately they don't use any kind of define flag for it that we could use to single it out and prevent the collision. I should touch bases with @mrdoob and other ThreeJS maintainers to have a more robust solution for the future. For the moment I'm removing the dependency to that function just because is a one-liner.
* I'm making look-at matrices right handed by default in OpenGL (GLSL). In the same way we have `LOOK_AT_RIGHT_HANDED` now we have `LOOK_AT_LEFT_HANDED` to change the default behavior. This is mostly after a quick google that confirms that right handed view matrices are default on OpenGL. So, I could be totally wrong and misguided.
* fix the …
> Tweaks and clips to make things work on ThreeJS

- lighting/raymarch/cast.glsl
- lighting/raymarch/cast.hlsl
As noted by IQ in his article [FBM detail in SDFs - 2019](https://iquilezles.org/articles/fbmsdf/)
> The problem with tradicional noise/fBM displacements on SDFs is this: the (regular, arithmetic) addition of two SDFs is not an SDF. Furthermore, the addition of an SDF and some other field/function (SDF or not) is also not an SDF (except for very carefully manufactured functions, that is). So, when adding a regular fBM, sine wave or any other displacement function to a "host" SDF, we don't get a valid SDF anymore (we violate the principle that the gradient of an SDF must have length 1.0).
That of course doesn't stop us from still trying, and we often do add arbitrary functions to our SDFs in the hopes of changing their shape. Sometimes we can achieve some level of success when done gently, …
> Option to take the absolute value of the SDF distance.

- math/mod.msl
`mod()` in Metal shaders is 0 for negative inputs because it's using `fmod()`.
Implement using `floor()`, the same way it's implemented for HLSL.
I created a simple fragment shader with the following code:
```c++
float3 modColor = float3(mod(st.x, 1));
float3 fmodColor = float3(fmod(st.x, 1));
float3 color = mix(fmodColor, modColor, step(0, st.y));
return float4(color, 1);
```
When centered at 0,0 and y in (-1,1), this generates:
Similar test for `float2` version:
> Make MSL mod() implementation match GLSL

- draw/digits.msl
- generative/srandom.msl
- math/atan2.msl
- math/mirror.msl
- math/mod2.msl
- sdf/opRepeat.msl
- space/bracketing.msl
- space/brickTile.msl
- space/checkerTile.msl
- space/windmillTile.msl
Some files that use the `mod()` function didn't `#include` it
Add the imports!
Imported each file on its own and built. Note that the build did not succeed for `bracketing.msl`, but that's due to other errors, which should be fixed in #253 .
> Add missing `mod()` imports for MSL files

- generative/psrdnoise.msl
- space/bracketing.msl
Fixes https://github.com/patriciogonzalezvivo/lygia/issues/252
I tested `psrdnoise()` with the following shader using the gradient output:
```c++
float3 color;
psrdnoise(float3(st * 4, time), 0, 0.1, color) * 0.5 + 0.5;
return float4(color, 1);
```
I don't have a great test case for `bracketing()`.
> Fix compile errors in bracketing.msl and psrdnoise.msl

- color/hueShift.wgsl
- color/space/srgb2lab.wgsl
- generative/pnoise.wgsl
- lighting/fresnel.wgsl
- space/rotate.wgsl
It appears that a numbr of WGSL modules have incorrect `#include` statements pointing to either HLSL or GLSL files.
Fixed the include directives to point to the correct language files.
> Fixed incorrect imports from copy-paste errors.
