patriciogonzalezvivo/lygia

generative/random.glsl
generative/random.hlsl

At least, I assume it's a typo...

Fix minor typo in random helpers

---

README.md

Some minor fixes while reading the README 🙏 
This project rocks, btw

Fixes some typos

---

color/space/rgb2hsv.hlsl

There were a few remaining glsl vec4

---

math/mod.hlsl

Add float version of HLSL mod

---

README.md

I saw some random typos here and there and decided to help on that. I also took some time to rearrange and reframe some sentences that were a bit hard to read. Hope this is useful!

Fix a bunch of small typos on README.md

---

lighting/raymarch.hlsl
lighting/raymarch/ao.hlsl
lighting/raymarch/camera.hlsl
lighting/raymarch/cast.hlsl
lighting/raymarch/default.hlsl
lighting/raymarch/map.hlsl
lighting/raymarch/material.hlsl
lighting/raymarch/normal.hlsl
lighting/raymarch/softShadow.hlsl
lighting/raymarch/volume.hlsl
sdf/cylinderSDF.hlsl
sdf/triPrismSDF.hlsl

Convert raymarching GLSL to HLSL 

---

README.md

I added a link to the [community post I did](https://derivative.ca/community-post/asset/lygia-touchdesginer/66804) about my implementation of Lygia in TouchDesginer. ✨

Added link to TouchDesigner implementation

---

README.md

Hello, got inspired today and created this sandbox as a starter template for lygia and react three fiber. Will use it for sure in the upcoming days and I would love anyone could use it as well:
https://codesandbox.io/s/lygia-react-starter-fftx6p
I added a link to the markdown in the src. I am also attaching the r3f.png image in case you need it.
Warm regards.

Added Link to Lygia React Template

---

README.md

This adds a new reference for TD, author details and small clarification

add static TD version references

---

README.md

Just corrected the dynamic TD entry to display my full name and changed the link from my github url to my website url ✨

Corrected Leith's name and website url

---

math/rotate3d.glsl
math/rotate3d.hlsl

just a minor text fix, replace 4s with 3s in rot3d docs

fix rotate3d docs - 4 > 3

---

space/bracketing.glsl

fix quotes around bracketing description
add "n" to orientation

fix quotes in bracketing.glsl yaml

---

space/bracketing.hlsl

sorry I did the glsl but forgot the hlsl

fix yaml description

---

generative/random.wgsl
generative/snoise.wgsl
math/grad4.wgsl
math/mod289.wgsl
math/permute.wgsl
math/taylorInvSqrt.wgsl

I went looking for a library like this a while ago, glad to see it finally exists :)

Port random and snoise to WGSL

---

sdf.glsl
sdf/arrow3DSDF.glsl
sdf/arrowSDF.glsl

I added one SDF for Arrow that can be used for debugging in 3D SDF, Raymarching or etc. I copy pasted the code from shadertoy example and put the original author in the file. Let me know if anything else is needed for this merging.

Add arrow 3D SDF for better debugging

---

lighting/raymarch/glass.glsl
lighting/raymarch/glass.hlsl
lighting/reflection.glsl
lighting/reflection.hlsl

Hi @patriciogonzalezvivo , I added a raymarching glass feature into the Lygia library so that others can use this easily in their raymarch render method! 🥳 Have a look at the example I added to this PR:
https://github.com/patriciogonzalezvivo/lygia_examples/pull/4
Let me know your thoughts! Can't wait to have this live!!!! 🚀

Raymarch Glass Feature 🎉

---

lighting/raymarch/glass.glsl
lighting/raymarch/glass.hlsl

Sorry that I missed out on the reflections. Now the reflections are fully working with these fixes. I will push the latest lygia_examples for this fix soon in this PR https://github.com/patriciogonzalezvivo/lygia_examples/pull/4

Raymarch Glass Reflections Fix

---

README.md

from issue #72:
added 2d integration examples (OGL, Three.js) using [Ssam/create-ssam](https://github.com/cdaein/create-ssam) packages.

Update README.md to add 2d integration examples

---

generative/random.glsl
generative/random.hlsl
generative/random.wgsl

Was reading through the code today and noticed that the RANDOM_SINLESS logic for 1D random was inverted. This PR fixes that inconsistency.
Thanks for the amazing library! 🙏

Fix 1D random use of RANDOM_SINLESS

---

sdf/juliaSDF.glsl
sdf/juliaSDF.hlsl

p5 sketch rendering Julia set.
https://editor.p5js.org/kfahn/sketches/7JslWNSIk

Add Julia set SDF

---

sdf/juliaSDF.glsl
sdf/juliaSDF.hlsl

It looks lovely with the spectral color:

Replace one value for c and add gist

---

sdf/triSDF.glsl
sdf/triSDF.hlsl

When rendering a triangle, I found that it was very small  (maybe just me?)  so I have increased the size of the triangle.

Increase size of returned triangle

---

sample/marchingSquares.glsl

Fixing some issues

---

filter/median/2D_fast5.hlsl
filter/noiseBlur.hlsl
generative/random.hlsl

sorry to keep spamming you with these!

more hlsl unity fixes

---

color/blend/color.glsl
color/blend/hue.glsl
color/blend/luminosity.glsl
color/blend/saturation.glsl

Adds 4 blending functions that are common in applications like Photoshop or Figma:
- Hue blend
- Saturation blend
- Luminosity blend
- Color blend

new blending functions: hue, sat, lum, color

---

space/brickTile.glsl
space/checkerTile.glsl
space/checkerTile.hlsl
space/windmillTile.hlsl

adding missing include for sqTile functions

add include sqTile

---

geometry/triangle/barycentric.glsl
geometry/triangle/intersect.glsl

fix some hlsl include to glsl in triangle.glsl and make_vec3 to vec3 in barycentric.glsl

fix some hlsl include to glsl in triangle.glsl and make_vec3 to vec3

---

lighting/pbrLittle.glsl
lighting/pbrLittle.hlsl

I've also updated the `.hlsl` file to keep shaders as similar as possible.

Fix 'smooth' reserved keyword #130

---

color/palette/hue.hlsl

Fixed hlsl version of hue.hlsl
* vec3 should be float3
* fract is frac in hlsl
* mod doesn't exist in hlsl. Using Lygia's math/mod.hlsl

Fixed hlsl implementation of color/palette/hue

---

lighting/iridescence.hlsl

Straightforward port of lighting/iridescence to hlsl.

Port of lighting/iridescence to hlsl.

---

color/palette/spectral.hlsl
color/space/w2rgb.hlsl
lighting/atmosphere.hlsl
lighting/blackbody.hlsl
lighting/wavelength.hlsl
math/mod2.hlsl

* Straightforward port of lighting/atmosphere to hlsl.
* Also ported math/mod2, which is a dependency of lighting/atmosphere.
* Straightforward port of lighting/blackbody to hlsl.
* Fixed syntax error in color/palette/spectral.hlsl
* Fixed hlsl version of color/space/w2rgb (port from glsl)
* Port of lighting/wavelength to glsl.

Various ports and fixes (HLSL)

---

sample/derivative.hlsl

derivative.hlsl was broken due to incorrect function calls (incorrect number of arguments.)

Fixed HLSL version of sample/derivative

---

lighting/raymarch/cast.hlsl

Exposed raymarching distance params in lighting/raymarch/cast.hlsl to align with glsl.

Exposed raymarching distance params (HLSL)

---

lighting/pbrLittle.glsl
lighting/pbrLittle.hlsl

Fixed pbrLittle.hlsl (unmatched #define) and updated to match glsl version

Fixed broken pbrLittle.hlsl and updated to match glsl version

---

math/const.glsl
math/const.hlsl
space/cart2polar.glsl
space/cart2polar.hlsl
space/polar2cart.glsl
space/polar2cart.hlsl

* Fixed cart2cart.glsl 3D (misnamed angles)
* Updated cart2cart.hlsl 3D to match glsl implementation
* Added polar2cart 3D (glsl and hlsl)
* Added degree/radians conversion constants.

Polar coordinates

---

lighting/raymarch/fog.glsl
lighting/raymarch/fog.hlsl
lighting/raymarch/render.glsl
lighting/raymarch/render.hlsl

Added various types of Raymarching fog, based on IQ's article, [better fog](https://iquilezles.org/articles/fog/).
No Fog
Constant density fog
Exponential height fog

Raymarching Fog

---

generative/noised.wgsl
generative/srandom.wgsl

A few questions:
- `srandom_tile2`, `srandom_tile3` are not in the HLSL file but are in the GLSL file. Should they be ported here?
- I added myself as the contributor to each and copied the names in the GLSL versions (as I copied and formatted those)

add: srandom, noised wgsl

---

color/mixSpectral.hlsl
color/palette/pigments.hlsl
color/space/rgb2hsl.hlsl
color/space/srgb2xyz.hlsl
color/space/w2rgb.hlsl
lighting/blackbody.hlsl
lighting/fresnelReflection.hlsl
lighting/iridescence.hlsl
lighting/pbr.hlsl
lighting/pbrLittle.hlsl
lighting/raymarch/render.hlsl
lighting/raymarch/volume.hlsl
math/inside.hlsl
math/mod2.hlsl
math/saturateMediump.hlsl
sample/normalFromHeightMap.hlsl
sample/triplanar.hlsl
sdf/mandelbulbSDF.hlsl
sdf/raysSDF.hlsl
space/kaleidoscope.hlsl
space/ratio.hlsl

* Fixed includes: *.glsl to *.hlsl
* Fixed types: vec* to float*

HLSL Fixes

---

space/lookAt.glsl
space/lookAt.hlsl
space/translate.glsl
space/translate.hlsl

* Fixed lookAt (inverted y-axis pointing downwards)
* Added handedness option (`LOOK_AT_RIGHT_HANDED`). Left-handed by default
* Refactored functions
Bonus:
* Added translate

Fixes and improvements to lookAt

---

DESIGN.md
generative/random.wgsl
generative/wavelet.wgsl
generative/worley.wgsl
math/dist.wgsl

WIP: implmenet wavelet, worley in WGSL and update docs

---

color/whiteBalance.msl

Just missed a mat3 :( Gonna be a lot of this lol.

Update White Balance -  Metal Bug Fix

---

lighting/pbrGlass.glsl
lighting/pbrGlass.hlsl

Minor necessary changes, from broken optimizations for RaspberryPI

Changes for compiling on RPI4

---

draw/digits.glsl
draw/digits.hlsl
draw/digits.msl

* Draw Vector digits
* Draw Matrix digits

debug vectors and matrices using digits

---

draw/digits.glsl
draw/digits.hlsl
draw/digits.msl
draw/matrix.glsl
draw/matrix.hlsl
draw/matrix.msl
draw/point.glsl
draw/point.hlsl
draw/point.msl

This two kind of functions are helpful to debug 2d/3d points and matrices (of 2, 3 and 4 dimensions)
https://github.com/user-attachments/assets/d40bb682-8016-4ab9-aed7-75b073decfd3
Can be tested with:
```glsl
#ifdef GL_ES
precision mediump float;
#endif
uniform vec3        u_camera;
uniform vec3        u_light;
uniform vec3        u_lightColor;
uniform vec2        u_resolution;
uniform vec2        u_mouse;
// SPACE
#define LOOK_AT_RIGHT_HANDED
#define LIGHT_DIRECTION     u_light
#define RESOLUTION          u_resolution
#define LIGHT_COLOR         vec3(0.95, 0.65, 0.5)
#define DIGITS_VALUE_OFFSET  vec2(-6.0, 3.0)
#define RAYMARCH_AMBIENT    vec3(0.7, 0.9, 1.0)
#define RAYMARCH_BACKGROUND (RAYMARCH_AMBIENT + rayDirection.y * 0.8)
#define PYRAMID_POS vec3(2.0, 0.10, 2.0)
#define CONE_POS …
```

add point and matrix draw functions

---

draw/colorPicker.glsl
draw/colorPicker.hlsl
draw/colorPicker.msl
draw/digits.glsl
draw/digits.hlsl
draw/digits.msl

Adding a flexible colorPicker for debugging 
https://github.com/user-attachments/assets/f3d476de-3da8-4534-8b41-598f71051fc3
https://github.com/user-attachments/assets/637c0bee-f101-42cc-8874-a075a5fc3582
https://github.com/user-attachments/assets/9ab12ff1-480d-47c5-9845-44ef4153a93b
https://github.com/user-attachments/assets/8013fa71-d2ea-4282-b427-95592ecf219b
Can be tested with:
```glsl
#ifdef GL_ES
precision mediump float;
#endif
uniform sampler2D   u_scene;
uniform mat4        u_viewMatrix;
uniform mat4        u_projectionMatrix;
uniform vec3        u_camera;
uniform vec3        u_light;
uniform samplerCube u_cubeMap;
uniform vec3        u_SH[9];
#ifdef LIGHT_SHADOWMAP
uniform sampler2D   u_lightShadowMap;
uniform mat4        u_lightMatrix;
varying vec4        v_lightCoord;
#endif …
```

ColorPicker

---

lighting/pbrClearCoat.glsl
lighting/pbrClearCoat.hlsl

Fixed breaking typo bug in pbrClearCoat (HLSL and GLSL).

Bug in pbrClearCoat

---

color/palette/flexoki.glsl
color/palette/flexoki.hlsl

Flexoki palette

---

package.json

all files into the npm package, not just dist
